### ISSUE TITLE
Running multiple callbacks asynchronously for a subscriber

### ISSUE THREAD

**Issue by bobthekingofegypt** [nats-io/asyncio-nats-streaming#16]
This is my first time using pythons asyncio and nats so I maybe not understand how everything should fit together but I was expecting the cb argument to be running async upto the max_inflight value.

For example in a script like this
```
import asyncio
import random
from nats.aio.client import Client as NATS
from stan.aio.client import Client as STAN

async def run(loop):
    nc = NATS()
    sc = STAN()

    await nc.connect(io_loop=loop)
    await sc.connect("test-cluster", "client-demo", nats=nc)

    async def cb(msg):
        wait_time = random.randint(0, 6)
        print("Wait time " + str(wait_time))
        await asyncio.sleep(wait_time)

        print("Received a message (seq={}): {}".format(msg.seq, msg.data))
        await sc.ack(msg)

    # Subscribe to get all messages from the beginning.
    await sc.subscribe("greetings", start_at='first', cb=cb, max_inflight=5, manual_acks=True, ack_wait=60)

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(run(loop))
    loop.run_forever()
```

If I published 5 messages onto the greetings channel I was hoping for 5 intertwined cb calls running together but they each run sequentially waiting for the previous one to finish.  Does the library support have multiple callbacks running in async?

**Comment by bobthekingofegypt** [comment]
For now I'm just creating a task inside cb to call a separate coroutine and ignoring the returned task value.

```
async def b(msg):
    wait_time = random.randint(0, 6)
    print("wait time " + str(wait_time))
    await asyncio.sleep(wait_time, loop=loop)
    print("Received a message (seq={}): {}".format(msg.seq, msg.data))
    await sc.ack(msg)

async def cb(msg):
    asyncio.create_task(b(msg))
```

Seems to work ok for now, I don't need to clean the tasks up on interrupt of the script anyway.

**Comment by wallyqs** [comment]
That approach is correct by the way, this library like other NATS client libraries process the messages sequentially with head of line blocking, concurrency could be increased as part of the logic from the callback as you mention.
