### ISSUE TITLE
Do NATS has asynchronous publisher in another language besides Python?

### ISSUE THREAD

**Issue by mcnl** [nats-io/asyncio-nats-streaming#23]
I was looking for an asynchoronous publisher code but I just find it in python? Do NATS have natively another asynchronous publisher implementation or example that is not in Python?

**Comment by wallyqs** [comment]
Sorry not following... the Go client also has support for async publishing as documented here: https://github.com/nats-io/go-nats-streaming#asynchronous-publishing

**Comment by mcnl** [comment]
Thank you, that was exactly what I was looking for.

**Comment by wallyqs** [comment]
great! ok will close this one then
