### ISSUE TITLE
ModuleNotFoundError: No module named 'google'

### ISSUE THREAD

**Issue by barrachri** [nats-io/asyncio-nats-streaming#3]
Using `docker run -it --rm python:3.6 bash`

```python
root@a104391a705f:/# pip install asyncio-nats-streaming
Collecting asyncio-nats-streaming
  Using cached asyncio-nats-streaming-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-zh3tfsa3/asyncio-nats-streaming/setup.py", line 2, in <module>
        from stan.aio.client import __version__
      File "/tmp/pip-build-zh3tfsa3/asyncio-nats-streaming/stan/aio/client.py", line 5, in <module>
        import stan.pb.protocol_pb2 as protocol
      File "/tmp/pip-build-zh3tfsa3/asyncio-nats-streaming/stan/pb/protocol_pb2.py", line 6, in <module>
        from google.protobuf.internal import enum_type_wrapper
    ModuleNotFoundError: No module named 'google'
```

**Comment by wallyqs** [comment]
The client has a couple deps
https://github.com/nats-io/asyncio-nats-streaming/blob/master/setup.py#L21

**Comment by barrachri** [comment]
Yep but even with `pip install protobuf asyncio-nats-streaming` it fails.

You need to install protobuf before and then asyncio-nats-streaming

**Comment by wallyqs** [comment]
you're right when running the tests too have to install the dependencies too
https://github.com/nats-io/asyncio-nats-streaming/blob/master/script/test.sh

**Comment by pvanderlinden** [comment]
This is a problem:
https://github.com/nats-io/asyncio-nats-streaming/blob/master/setup.py#L2

**Comment by hidai** [comment]
I saw the fix, but when will it be available with pip-install?

**Comment by wallyqs** [comment]
@hidai right, nothing really holding this so just cut a release with the change tagged as `v0.1.2`

**Comment by hidai** [comment]
Thanks wallyqs, pip-install works now!
