### ISSUE TITLE
examples/basic.py returns None

### ISSUE THREAD

**Issue by aharol** [nats-io/asyncio-nats-streaming#4]
I am trying to run the the `examples/basic.py`, which shows nothing on a screen (no print statement is executed). Running stan server in debug mode using `-SD` flag, I see the client connecting to the stream, successfully subscribing, removing subscription and closing down. At the same time, adding an extra line `await asyncio.sleep(0.1)` after `await sc.subscribe` prints the result successfully, which makes me think that the execution of `run` finishes before stan returns any results. Could you comment on this?

**Comment by jsam** [comment]
None of the examples do NOT work for me either. Can we get any input on this from the team?

**Comment by wallyqs** [comment]
Updating the examples in this branch here https://github.com/nats-io/asyncio-nats-streaming/blob/example-updates/examples/basic.py
I'll make another pass to the examples today

**Comment by wallyqs** [comment]
@jsam made updates to the `basic.py` example so that the output is visible, thanks for the report

**Comment by jsam** [comment]
thanks. probably updating the readme makes sense as well?

**Comment by wallyqs** [comment]
good call, just updated as well 👍

**Comment by jsam** [comment]
thank you! 💃
