### ISSUE TITLE
Library reconnects only once

### ISSUE THREAD

**Issue by pvanderlinden** [nats-io/asyncio-nats-streaming#7]
I can not get reconnects working, I have tested it with a program publishing and consuming, if I shut down the server for a few seconds, they both will stop working (the publisher will timeout on publishing, the consumer will just not receive any messages anymore)

Connection code:
```
from functools import partial


async def test_cb(cb_type, *args, **kwargs):
    print(cb_type, args, kwargs)

nc = NATS()
await nc.connect(io_loop=loop, error_cb=partial(test_cb, 'error'), disconnected_cb=partial(test_cb, 'disconnect'), closed_cb=partial(test_cb, 'closed'), reconnected_cb=partial(test_cb, 'reconnect'), ping_interval=25)
```

Output:
```
error (NatsError('nats: empty response from server when expecting INFO message',),) {}
reconnect () {}
error (<class 'nats.aio.errors.ErrStaleConnection'>,) {}
disconnect () {}
error (NatsError('nats: empty response from server when expecting INFO message',),) {}
error (ConnectionRefusedError(111, "Connect call failed ('127.0.0.1', 4222)"),) {}
disconnect () {}
closed () {}
```

What I understand from the defaults it should try to reconnect 10 times with a delay of 2 seconds, which means if the server is down for less then 20 seconds it should at least reconnect and resume operation, unfortunately it won't resume operation (the consumer will just not receive anything anymore, the producer will timeout on a publish call, even when the server is back up again).

**Comment by wallyqs** [comment]
Thanks for the report, I'll take a look at it today.

**Comment by pvanderlinden** [comment]
Is there a cause known? Is this maybe actually a bug for the base NATS?

**Comment by wallyqs** [comment]
Yes, this looks like to be an issue from the underlying nats client https://github.com/nats-io/asyncio-nats need to revise the reconnection logic against already failed servers and update.
